import "react-toastify/dist/ReactToastify.css";
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { ToastContainer } from "react-toastify";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Figma hardware bridge",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen w-screen flex-col bg-stone-100 p-4 pb-12 dark:bg-stone-800">
        <TRPCReactProvider source="next-js">{children}</TRPCReactProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
